config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/new'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :entries
  resources :users do
    resources :entries
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :entry

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :categories, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
  validate :image_size
  scope :only_private, -> { where(published: false) }
  scope :only_public, -> { where(published: true)}

  #validates :user_id, presence: true
  #belongs_to :user  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader

  def country_name
   country = self.country
   ISO3166::Country[country]
  end


  def self.search(search)
    if search
      where("dream_category LIKE ? OR content LIKE ?
      OR country LIKE ? OR created_at LIKE ?", "%#{search}%", "%#{search}%",
      "%#{search}%", "%#{search}%")
      #where("content LIKE ?", "%#{search}%")
      #where("country LIKE ?", "%#{search}%")
      #where("created_at LIKE ?", "%#{search}%")
    else
      all
    end
  end


  private

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should not exceed 5MB")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  validates :email, presence: true
  has_many :entries, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #:omniauthable, :omniauth_providers => [:facebook]
=begin
 def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.user_name = auth.info.user_name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image

  end
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def password_required?
    super && self.blank?
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def after_sign_in_path_for(resource)
  new_entry_path
end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category  = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.save
  end






private
  def category_params
    params.require(:category).permit(:name, :entry_id)
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = Entry.all
    @entries = Entry.search(params[:search])
    @entries = Entry.only_public
    @entries = Entry.only_private

  end


  def new
    @entry = current_user.entries.build
  end

  def create
    @entry = current_user.entries.build(entry_params)

    if @entry.save
      flash[:success] = "Entry successfully created. "
      redirect_to entries_path
    else
      render :new
    end
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def destroy
    if @entry.destroy
      flash[:success] = "Entry deleted"
      redirect_to  entries_path
    else
      render :destroy
    end

  end


  private

  def entry_params
    params.require(:entry).permit(:content, :image, :dream_category, :country, :published)
  end

  def set_entry
    @entry = Entry.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :country)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
=begin
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  # You need to implement the method below in your model (e.g. app/models/user.rb)
  @user = User.from_omniauth(request.env["omniauth.auth"])

  if @user.persisted?
    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  else
    session["devise.facebook_data"] = request.env["omniauth.auth"]
    redirect_to new_user_registration_url
  end
end

def failure
  redirect_to root_path
end
end
=end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert alert-warning alert-dismissible fade in',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: @user.user_name, class: "gravatar")
  end
end

app/views/entries/index.html.erb
<body class="body">
<div class="posts-wrapper row">
  <% @entries.each do |entry| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          <%= entry.user.user_name %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag entry.image.url, class:'img-responsive'), entry_path(entry) %>
      </div>
      <p class="caption">
          <%= entry.content %>
      </p>
      <div class="time">
      <span class="timestamp">
        Posted- <%= Time.zone.now.strftime("%B %e, %Y at %I:%M %p") %><br>
        Category- <%= entry.dream_category %><br>
        Location- <%= entry.country %>
      </span>
    </div>

      <span class="delete">
        <% if current_user %>
        <%= link_to "Delete", entry, method: :delete,
                                    data: {confirm: 'Are you sure?'} %>
        <% end %>
        </span>
    </div>
      <% end %>
      <% @entries.each do |entry| %>
        <<%= entry.content %></p>
      <% end %>
</div>
</body>

app/views/entries/new.html.erb
<body class="body">
<div class="deviselink">
  <div class="posts-wrapper">
    <div class="post">
      <div class="post-body">
        <div class="image-wrap">
          <%= image_tag 'waterfall.jpg', id: 'image-preview', class: 'img-responsive' %>
           <h1>Enter a dream</h1>
    <%= simple_form_for @entry do |f| %>
    <div class="row">
     <div class="col-md-12 text-center">
      <%= f.error_notification %>
      <div class="container-fluid">
       <div class="form-group text-center">
         <i class="fa fa-eye fa-lg"><h4>Visibility</h4><br>
          <%= f.radio_button :published, 'Public' %> Public
          </i>
          <h4>Upload an image:</h4>
          <%= f.input :image, accept: 'image/jpg,image/gif,image/png', label: false,
           input_html: { onChange: 'loadFile(event)'} %>
    </div>
      <div class="form-group text-center">
      <%= f.input :content,  label: false, placeholder: 'Write about your dream here...', input_html: { class: 'input-lg' },
          class: 'form-control' %>
          <h4>What kind of dream?</h4>
      <%= f.select :dream_category, ['Worldly', 'Flying', 'Spiritual', 'Sex', 'Love', 'Death', 'Nightmare'], {}, class: 'form-control' %>
    </div>
    <div class="form-group text-center">
      <h4>Country</h4>
      <%= country_select("entry", "country", { priority_countries: ["GB", "FR"], selected: "GB" },
      { class: 'form-control', data: { attribute: "value" } }) %>
      <%= f.button :submit, class: 'btn-success' %>
    </div>
    <% end %>
  </div>
</div>
</div>
  </div>
</div>
</div>
</body>

app/views/entries/search.html.erb
<% if @entries.present? %>
  <%= render @entries %>
<% else %>
  <p>There are no entries containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/entries/show.html.erb
<%= @entry.content %>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                     <span class="light">Dreamshare</span> 

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                      <% if user_signed_in? %>
                         <li><%= link_to "New Dream", new_entry_path, class: 'page-scroll' %></li>
                         <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'page-scroll' %></li>
                      <% else %>
                         <li><%= link_to "Login" , new_user_session_path, class: 'page-scroll' %></li>
                         <li><%= link_to "Register", new_user_registration_path, class: 'page-scroll'  %></li>
                      <% end %>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#search">Search</a>
       
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
              
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dreamshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
	



<%= render 'layouts/header' %>
<div class="flash">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
</div>

  <%= yield %>


</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dreamshare</title>

    <!-- Bootstrap Core CSS -->
    <!--
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <!--
    <link href="css/grayscale.css" rel="stylesheet">
-->
    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<!--
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <!--
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                     <span class="light">Dreamshare</span> 

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <!--
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <!--
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                      <% if user_signed_in? %>
                         <li><%= link_to "New Dream", new_entry_path, class: 'page-scroll' %></li>
                         <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'page-scroll' %></li>
                      <% else %>
                         <li><%= link_to "Login" , new_user_session_path, class: 'page-scroll' %></li>
                         <li><%= link_to "Register", new_user_registration_path, class: 'page-scroll'  %></li>
                      <% end %>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <!--
                    <li>
                        <a class="page-scroll" href="#download">Download</a>
                    </li>
             
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
              
                </ul>
            </div>
            <!-- /.navbar-collapse -->
            <!--
        <!-- /.container -->
        <!--
    </nav>
-->

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Dreamshare</h1>
                        <p class="intro-text">What if we could hear each others dreams</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <a id="about_dreamshare">
                <h2>About Dreamshare</h2>
                <p>Dreamshare is an interactive web based application allowing users to share their dreams (during sleep) through text and images (associated by category) with the world, and gain insight (from interacting with others) into the collective unconscious and it's workings.</p></a>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="search" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Search for Dreams</h2>
                    <p>You can search for dreams by category, date, and location to find patterns.</p>
                    <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Search Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <a id="contact_us">
                <h2>Contact Us</h2>
                <p>Feel free to email us if you have any questions, or if you just want to say hello!</p>
                <p><a href="mailto:jeremy.rmrr@gmail.com">jeremy.rmrr@gmail.com</a>
                </p></a>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/jemlife" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/jeremy.greenwood.52" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <!--
    <div id="map"></div>
-->

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Dreamshare 2016</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

</body>

</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<body class="body2">
<h1>
  <%= gravatar_for @user %>
  <%= @user.user_name %>
</h1>
</body>